### ISSUE TITLE
Do not escape HTML

### ISSUE THREAD

**Issue by sharpaper** [readthedocs/commonmark.py#166]
How can I avoid HTML escaping? For example

    **foo**
    <div>
        **bar**
    </div>

`foo` is emphasized but `bar` is not, and the `<div>` is escaped to `&lt;div&gt;`. I would like to leave the HTML as-is, and convert everything else.

**Comment by yujiri8** [comment]
It's been a few months and it looks like the `<div>`s are not escaped anymore, but the `**bar**` is still not processed. It seems to work if you add blank lines around the content of the `<div>` (I've discovered this in other markdown processors, like mistune).
