### ISSUE TITLE
Do not hide link labels

### ISSUE THREAD

**Issue by sharpaper** [readthedocs/commonmark.py#195]
Sorry but how can I *not* hide link labels? For instance

    [foo][bar]
    ...
    [bar]: http://foo.bar "foo bar"

is turned into a link, but I want to keep the foot reference visible. What happens is that they are hidden, not rendered in the output.

**Comment by sharpaper** [comment]
Probably what I'm looking for is "footnotes"? How do I insert a footnote? The syntax `[^1]` does not seem to work.

**Comment by nikolas** [comment]
Someone might be able to help you by asking this question here as well: https://talk.commonmark.org/
