### ISSUE TITLE
Support for YAML front-matter

### ISSUE THREAD

**Issue by dend** [readthedocs/commonmark.py#208]
Currently, when getting the AST for a Markdown file with YAML front-matter, the content is not identified as such.

<img width="860" alt="image" src="https://user-images.githubusercontent.com/1389609/66278833-af2dd900-e861-11e9-82ec-59bc3fe68358.png">

`thematic_break` is seen first, but after that the closing `---` is not properly identified and is seen as part of the header.

**Comment by sylvestre** [comment]
Simple test case
```
import commonmark
parser = commonmark.Parser()
with open('index.md', 'r') as f:
    read_data = f.read()
ast = parser.parse(read_data)

renderer = commonmark.HtmlRenderer()
html = renderer.render(ast)
print(html)
```

With index.md
```
---
layout: default
title: Using GeckoView
nav_order: 3
---

# my doc imported from jekyll

We are working on providing detailed usage documentation for all of GeckoView's most popular features. Here is what we have so far.
```

Generates
```
<hr />
<h2>layout: default
title: Using GeckoView
nav_order: 3</h2>
<h1>my doc imported from jekyll</h1>
```

**Comment by 15228945545** [comment]
> Currently, when getting the AST for a Markdown file with YAML front-matter, the content is not identified as such.
> 
> <img alt="image" width="860" src="https://user-images.githubusercontent.com/1389609/66278833-af2dd900-e861-11e9-82ec-59bc3fe68358.png">
> 
> `thematic_break` is seen first, but after that the closing `---` is not properly identified and is seen as part of the header.

**Comment by sylvestre** [comment]
Here is what i implemented for Firefox 
https://searchfox.org/mozilla-central/rev/2e355fa82aaa87e8424a9927c8136be184eeb6c7/tools/moztreedocs/__init__.py#127

If a fm header is found, extract the data and inject it in the markdown file

**Comment by chrisjsewell** [comment]
Note that front matter is supported by https://myst-parser.readthedocs.io/en/latest/using/syntax.html#front-matter (as used by [jupyterbook](https://jupyterbook.org))
