### ISSUE TITLE
Consider add implementation of sub/sup tags

### ISSUE THREAD

**Issue by rmuslimov** [readthedocs/commonmark.py#85]
I found that this http://pandoc.org/MANUAL.html#superscripts-and-subscripts feature might be useful, do you think if it's good idea add implementation of this?

**Comment by nikolas** [comment]
This library closely follows the [CommonMark spec](http://spec.commonmark.org/).. for features like this you can suggest them here: https://talk.commonmark.org/c/spec

If we can implement this feature as some sort of extension to the core parser, like a post-processing step, then we could include it here.
